### ISSUE TITLE
basic question - no input file

### ISSUE THREAD

**Issue by riphraph** [OOW/SWMMout2csv#8]
Hi, 
Sorry for this very basic question. My .out file is not recognized. 
I have placed the .out file above the program file, specified the input and outpath, as you can see on the attached file.
![Question_Swmmout2csv](https://user-images.githubusercontent.com/52968170/61304569-5fd29200-a7b7-11e9-9c34-62075c454f79.PNG)
Thanks,

**Comment by shanninio-jing** [comment]
Hi,
It seems like the 'parameter_name' column was deleted in your input file. The reader will look for certain parameter names to read in the input for each parameter. So add the parameter names back and try again. (Place the input values in Column B instead of Column A)

Also make sure the updated input file is saved in the right format. Each column should be separated by a comma as it's a csv file. I will recommend to double check the format in a text editor after updating it in Excel. 
![image](https://user-images.githubusercontent.com/18667657/61308085-7f6cb900-a7bd-11e9-9dd4-59144e5dcb6b.png)

Thanks

**Comment by riphraph** [comment]
Hi, 
Thanks for your reply , that helped me find out my CSV files are made with ; instead of commas. 
I believe my input file is in the right format now, since i am now stuck on another issue on the number describing the extract subcatchments line. 
The value 1 or 0 is not read correctly. 
Do you have any suggestion ?

Thanks again,
![Question_Swmmout2csv](https://user-images.githubusercontent.com/52968170/61321400-6f62d280-a7d9-11e9-9020-5dc233d5d33d.PNG)

**Comment by shanninio-jing** [comment]
It's probably still the format issue. For extract option, the reader will expect 0 or 1 as the input, otherwise it will throw out this error. I just tested this tool to make sure it's still working. I've attached a screenshot of input parameters that I used to setup the tool. I also made it open in text editor so that you could compare the difference. 
![image](https://user-images.githubusercontent.com/18667657/61323084-23b22800-a7dd-11e9-87e5-3840b38577ff.png)
![image](https://user-images.githubusercontent.com/18667657/61323122-388ebb80-a7dd-11e9-81a9-54572a966c95.png)

It works and here is the result:
![image](https://user-images.githubusercontent.com/18667657/61323215-68d65a00-a7dd-11e9-8f88-6a949b0ad7d7.png)

Sorry that I can't share the test .out file with you as it's our internal file. I can't share it to public without permission.

Let me know if you need further help.

Best,
Jing

**Comment by shanninio-jing** [comment]
[input_parameter_issue8.zip](https://github.com/OOW/SWMMout2csv/files/3398785/input_parameter_issue8.zip)
I setup an input parameter file for you based on the information I got from your screenshot. Try this to see if it works for you or not.

**Comment by riphraph** [comment]
Yes, that works. Also, i used GoogleSheet to export my csv (with commas instead of semi colons), and it works well. 
Thanks again,
