### ISSUE TITLE
Program is not runnig

### ISSUE THREAD

**Issue by rajukhad** [OOW/SWMMout2csv#9]
I am totally new to this platform. I tried to run the program even tried to get help  by seeing the previous issues but each time I run the file I got the following error  in run windows

C:\WINDOWS\system32>SWMMout2csv_087.exe SWMMout2csv_input_087.csv
'SWMMout2csv_087.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>pause
Press any key to continue . . .

Can anybody provide the solutions for this?

**Comment by shanninio-jing** [comment]
Hi,

Have you tried to unzip the file before running the batch?

**Comment by rajukhad** [comment]
Yes I do and provide the input parameters as learn from the issue 1.

**Comment by shanninio-jing** [comment]
I must admit that it is difficult to pinpoint your issue since I'm not sure about your system settings. It seems like a directory issue. your batch was running under C:\WINDOWS\system32 instead of the actual directory it's sitting in (I'm assuming the files are not saved at C:\WINDOWS\system32). The batch failed to find the executable (SWMMout2csv_087.exe). This usually happens when I run it as an administrator.  I will suggest to supply full path in your batch or add some code to the top of the batch to change the working directory

**Comment by rajukhad** [comment]
Changing the path followed by not running as administrator works for me.Thank you.
